package dev.tauri.jsg.api.helper.dimension;

import dev.tauri.jsg.api.stargate.network.StargatePos;
import dev.tauri.jsg.api.stargate.network.address.StargateAddress;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.Level;

import javax.annotation.Nullable;
import java.util.List;
import java.util.Map;

/**
 * Interface for managing stargate dimensions.
 * <p>
 * Each stargate leads to a unique dimension. If no dimension exists for a given
 * stargate address, a new one is created dynamically. Connections between two
 * stargates within the same dimension are not allowed.
 * <p>
 * Developers can register custom dimensions with fixed stargate addresses and
 * predefined dimension configurations (biomes, ores, properties).
 */
public interface IStargateDimensionManager {

    /**
     * Gets or creates a dimension for the given stargate address.
     * If the dimension does not exist yet, it will be created using the provided
     * or default configuration.
     *
     * @param address The stargate address to resolve to a dimension.
     * @return The ServerLevel for the target dimension, or null if creation failed.
     */
    @Nullable
    ServerLevel getOrCreateDimension(StargateAddress address);

    /**
     * Gets the dimension associated with a stargate address without creating it.
     *
     * @param address The stargate address to look up.
     * @return The ResourceKey for the dimension, or null if not mapped.
     */
    @Nullable
    ResourceKey<Level> getDimensionForAddress(StargateAddress address);

    /**
     * Checks whether a given stargate address is mapped to an existing dimension.
     *
     * @param address The stargate address to check.
     * @return true if a dimension exists for this address.
     */
    boolean hasDimension(StargateAddress address);

    /**
     * Checks whether two stargate positions are in the same dimension.
     * Connections within the same dimension are not allowed.
     *
     * @param source The source stargate position.
     * @param target The target stargate position.
     * @return true if both stargates are in the same dimension.
     */
    boolean isInSameDimension(StargatePos source, StargatePos target);

    // -----------------------------------------------------------------------
    // Custom Dimension Registration
    // -----------------------------------------------------------------------

    /**
     * Registers a custom dimension with a fixed stargate address and configuration.
     * This allows developers to add their own dimensions accessible via specific
     * stargate addresses.
     *
     * @param entry The custom dimension entry containing ID, addresses, and config.
     */
    void registerCustomDimension(CustomDimensionEntry entry);

    /**
     * Unregisters a custom dimension entry.
     *
     * @param dimensionId The resource location of the dimension to unregister.
     * @return true if the dimension was found and removed.
     */
    boolean unregisterCustomDimension(ResourceLocation dimensionId);

    /**
     * Gets the custom dimension entry for a given dimension ID.
     *
     * @param dimensionId The resource location of the dimension.
     * @return The custom dimension entry, or null if not registered.
     */
    @Nullable
    CustomDimensionEntry getCustomDimension(ResourceLocation dimensionId);

    /**
     * Gets all registered custom dimension entries.
     *
     * @return An unmodifiable map of dimension IDs to their entries.
     */
    Map<ResourceLocation, CustomDimensionEntry> getCustomDimensions();

    // -----------------------------------------------------------------------
    // Dimension Configuration
    // -----------------------------------------------------------------------

    /**
     * Sets the default configuration used for dynamically created dimensions
     * when no specific configuration is provided.
     *
     * @param config The default dimension configuration.
     */
    void setDefaultDimensionConfig(StargateDimensionConfig config);

    /**
     * Gets the default dimension configuration.
     *
     * @return The default dimension config.
     */
    @Nullable
    StargateDimensionConfig getDefaultDimensionConfig();

    /**
     * Gets the dimension configuration for a specific dimension.
     * Returns the custom config if registered, otherwise the default config.
     *
     * @param dimensionId The resource location of the dimension.
     * @return The dimension config, or null if none is set.
     */
    @Nullable
    StargateDimensionConfig getDimensionConfig(ResourceLocation dimensionId);

    /**
     * Gets all dimensions that were dynamically generated by the stargate system.
     *
     * @return A list of resource keys for dynamically generated dimensions.
     */
    List<ResourceKey<Level>> getGeneratedDimensions();
}
